### ISSUE TITLE
Enhance readme / documentation

### ISSUE THREAD

**Issue by bmitch** [bmitch/churn-php#104]
I'm open to reviews of the readme if anyone has any suggestions.

* Any information missing or instructions missing.
* Better layout/design/look.
* Anything else you'd like to see in the readme.

**Comment by enygma** [comment]
There's not a mention of how to run the tests in there. I know it's a little thing but it could help some out there doing dev on the library.

Also, not so much a `README` related thing but I noticed there's also some sorting functionality in the `ResultsCollection`. Any plans to add that as an optional param on the command line call?

**Comment by bmitch** [comment]
@enygma Thanks for the feedback.

* I do have a note about the tests in the https://github.com/bmitch/churn-php/blob/master/CONTRIBUTING.md but it could be more front and centre in the readme. So that is a good point.

* The `ResultsCollection` sorts the results so the top scoring files show first. I don't have any plans to add that as a configurable option at this time (I am not sure why having sorted the other way would be wanted) but I am open to it if enough people request it.

* Yeah that is a good idea.

If you like feel free to open an issue for any of these or send in a pull request and I'd be happy to look at them!

**Comment by bmitch** [comment]
@enygma 

I added a small section on running tests in the readme (see https://github.com/bmitch/churn-php/blob/master/README.md#tests) is this kind of what you were thinking of?

I also opened an issue for the user to be able to define where the config file lives (#108).

**Comment by enygma** [comment]
@bmitch I see the link at the top of the `README` for the "Tests" but it doesn't look like the section actually exists.

**Comment by bmitch** [comment]
@enygma Ah thanks for catching that, I just changed that and added the testing info under the `Contributing` header. I'll update the readme now.

**Comment by bmitch** [comment]
Closing this for now. If any other issues come up I welcome new issues.
