### ISSUE TITLE
Option to define where the config file `churn.yml` lives

### ISSUE THREAD

**Issue by bmitch** [bmitch/churn-php#108]
See the original comment here:

https://github.com/bmitch/churn-php/issues/104#issuecomment-332836353

**Comment by ghosh** [comment]
Hey, I can help with this. Where would the option be defined?

**Comment by bmitch** [comment]
@ghosh Great thanks. I think there should still be a default location. So if the user doesn't specify anything then it just acts as is does not.

Perhaps a command line option?

`vendor/bin/churn run src tests -c <path to file>`
`vendor/bin/churn run src tests --configuration <path to file>`

Something like that?

**Comment by ghosh** [comment]
Yup, that makes sense. Thanks. I'll pick this up tomorrow.

**Comment by bmitch** [comment]
Thanks very much.

**Comment by bmitch** [comment]
Implemented in #109
