### ISSUE TITLE
Bug in FileManager - regex to ignore files?

### ISSUE THREAD

**Issue by bmitch** [bmitch/churn-php#113]
I think if you try to make a regex pattern like `*.php` to ignore files it won't give you the expected results.

I created this test:

```
        $fileManager = new FileManager(['php', 'inc'], ['Assets2/*.php']);
        $this->assertCount(1, $fileManager->getPhpFiles([__DIR__ . '/../Assets2']));
```

Which I would expect to pass but it fails.

**Comment by bmitch** [comment]
@bearzk Not sure if this is something you'd like to look at. If not I can take a look into it.

I created a branch with a test that I would expect to pass in case you want to look:

https://github.com/bmitch/churn-php/blob/bmitchell-113/tests/Unit/Managers/FileManagerTest.php#L78-L79

**Comment by berkedel** [comment]
What behavior `*` has in this case? Does it match the pattern only in current directory or also recursively match in subdirectories?

**Comment by bearzk** [comment]
@bmitch sure, I made another PR https://github.com/bmitch/churn-php/pull/121 for this. Should have covered this case.

**Comment by bearzk** [comment]
@berkedel it would match recursively.
