### ISSUE TITLE
New screenshot

### ISSUE THREAD

**Issue by bmitch** [bmitch/churn-php#115]
Still not entirely happy with the screenshot in the readme.md

* It has a command prompt at the top and the bottom. Could remove both, neither are really needed.
* It contains a really long file name (the `CyclomaticComplexityAssessor.php`) in the results which forces the table to be very wide. If that file was ignored the table would be smaller in width which I think would improve the screenshot.

**Comment by dbrereton1995** [comment]
I'll do this 👍

**Comment by vrishank97** [comment]
Can I take this up?

**Comment by bmitch** [comment]
@vrishank97 Yeah sure, thanks.

**Comment by bmitch** [comment]
@vrishank97 if you are still interested in this, I just updated the master branch with the new scoring algorithm. So if you can use that branch it would be best. Thanks!
