### ISSUE TITLE
Update readme to reflect new configuration location option.

### ISSUE THREAD

**Issue by bmitch** [bmitch/churn-php#117]
This feature was added in #109.

The readme file needs to be updated to reflect this.

**Comment by tulikavijay** [comment]
I would like to be assigned on this :)

**Comment by bmitch** [comment]
@tulikavijay Go for it! :+1:

**Comment by tulikavijay** [comment]
I would like to ask the particular command for this...is it this one 
vendor/bin/churn run -c **path**
sorry i am new to this, I tried to read the code to figure it out but couldn't find anything.

**Comment by bmitch** [comment]
@tulikavijay Yep that is the one.

```
  -c, --configuration[=CONFIGURATION]  Path to the configuration file [default: "churn.yml"]
```

**Comment by bmitch** [comment]
This is complete.
