### ISSUE TITLE
Build a "binary" for this project

### ISSUE THREAD

**Issue by matthiasnoback** [bmitch/churn-php#126]
It would be awesome if one could run this tool against a code base without installing it (if said project supports Composer dependencies at all ;)). Sounds like a `.phar` file would be useful. I'll look into what's needed for that and if we can make the build process automated.

**Comment by matthewbaggett** [comment]
@matthiasnoback I just `composer global require` install things and then put ~/.config/composer/vendor/bin into my PATH.

**Comment by matthiasnoback** [comment]
@matthewbaggett That's a viable solution, but past experiences have learned me that this can lead to some impossible to solve dependency issues due to incompatible globally installed packages. Hence, for tools like this, I do like to have a .phar handy ;)
