### ISSUE TITLE
Enable PDS compliance

### ISSUE THREAD

**Issue by raphaelstolt** [bmitch/churn-php#128]
Enable [PDS](http://php-pds.com) compliance by moving `churn` and the `CyclomaticComplexityAssessorRunner` into a dedicated `bin` directory.

**Comment by bmitch** [comment]
@raphaelstolt `churn` should already be in the `bin` folder after you install it. (Correct me if I am wrong).

`CyclomaticComplexityAssessorRunner` could be moved to `bin` in the same way if that will make it PDS compliant. 

Is that something you are interested in sending a pull request for?

**Comment by raphaelstolt** [comment]
Not talking about the `vendor/bin` directory but rather adding a dedicated `bin` directory to the package repository as summarised [here](https://github.com/php-pds/skeleton/tree/1.0.0#summary).

Migth send a PR your way soonish.

**Comment by bmitch** [comment]
That would be great, thanks @raphaelstolt

**Comment by bmitch** [comment]
Fixed by #139
