### ISSUE TITLE
CyclomaticComplexityAssessor - Improve by using something like `nikic/PHP-Parser`

### ISSUE THREAD

**Issue by villfa** [bmitch/churn-php#146]
The score is calculated by using regular expressions which leads to errors.

Example of a PHP file containing only a comment:
```php
<?php
// if ( if ( if (
```
In this example the score is 3 whereas it should be 1.

This kind of error could be avoided by using [PHP-Parser](https://github.com/nikic/PHP-Parser).

**Comment by bmitch** [comment]
Thanks @villfa - please feel free to submit a PR if you like. Otherwise I will get to it when I can.

**Comment by bmitch** [comment]
Perhaps we can use `nikic/PHP-Parser` to analyse the PHP file being assessed and not have to rely on regular expressions? Should be something interesting to work on.

**Comment by bmitch** [comment]
Started a new branch `bmitchell-146` with a new test that has the above code provided by @villfa:

https://github.com/bmitch/churn-php/blob/bmitchell-146/tests/Unit/Assessors/CyclomaticComplexity/CyclomaticComplexityAssessorTest.php#L89-L93

Can use that as a starting point for a new CyclomaticComplexityAssessor that would use `PHP-Parser` or something similar.

**Comment by emilv** [comment]
I think you should use php-ast instead of php-parser.

**Comment by bmitch** [comment]
@emilv I've never used either package so I don't know the pros and cons of each. Why would you chose `php-ast`?

**Comment by emilv** [comment]
php-ast uses the native PHP abstract syntax tree. Both are maintained by nikic, a PHP core developer (who also introduced the formal parser into the core PHP runtime!).

Nikic have written about the differences here: https://github.com/nikic/php-ast#differences-to-php-parser

But reading that list makes me doubt my own suggestion. Perhaps PHP-Parser is the right choice after all?

**Comment by bmitch** [comment]
Thanks @emilv that link is a huge help. I will take a deeper look as soon as I have time.

**Comment by bmitch** [comment]
I think using PHP-Parser is probably going to be the better choice. PHP-ast is a PHP extension. I think to keep this as accessible as possible it is better to use PHP-Parser because it doesn't require an extension to be installed.
