### ISSUE TITLE
Possible problem in cyclomatic complexity calculation

### ISSUE THREAD

**Issue by firoxer** [bmitch/churn-php#148]
Hi, I skimmed through the code and noticed something. It looks like this method does something else than what its docblock says: https://github.com/bmitch/churn-php/blob/refactor/src/Assessors/CyclomaticComplexity/CyclomaticComplexityAssessor.php#L46-L49

It seems to add a maximum of one to the total score even if there are multiple methods/`function`s in the file.

If the code is wrong, let me know so I can send a PR to fix it!

**Comment by bmitch** [comment]
@firoxer yep you're right. The method name is misleading.

Maybe a better name like 'hasAtLeastOneMethod()` would be better?

**Comment by firoxer** [comment]
Yeah, that does sound better!

**Comment by firoxer** [comment]
I'll leave the issue open as a reminder. Close it if you find it unnecessary :)

**Comment by bmitch** [comment]
Thanks @firoxer fixed in #150
