### ISSUE TITLE
We get linear scores

### ISSUE THREAD

**Issue by emilv** [bmitch/churn-php#149]
Just installed version 0.3.1. I don't think our scores are correct:

![skarmdump 2017-10-12t10 12 55](https://user-images.githubusercontent.com/1684914/31485935-ed9d22b6-af35-11e7-95d4-bde6b12b7e99.png)

The score just looks like the sum of Times Changed and Complexity. Looking at the code I believe it should be an Euclidean distance in a 2-dimensional plane.

**Comment by emilv** [comment]
Never mind, the new scoring is apparently not released yet. Looking forward to the improved metric!

**Comment by bmitch** [comment]
@emilv that's correct, the new scoring is in master branch and not released yet. I am trying to get some refactoring done before I release it as a new major version. Hopefully soon :)
