### ISSUE TITLE
No results - script hangs forever

### ISSUE THREAD

**Issue by iquito** [bmitch/churn-php#172]
I tried today to test out churn-php in one of my projects, but when executing `vendor/bin/churn run src` the script just runs forever (one CPU is at 100% during that time) and never returns a result. I tried waiting one hour, but even then it is not finished, so I suspect this is a bug.

My used software and project details:

- PHP 7.2.1
- churn-php 0.4.1
- 1600 commits in the project
- 1715 files and 320 directories in /src

Not sure if maybe PHP 7.2 is the reason for these problems?

**Comment by iquito** [comment]
Maybe these help to:

- Using Symfony 3.4.3
- Using git as versioning system
- Using Debian Linux as operating system
- No configuration file used

**Comment by bmitch** [comment]
Thanks for the report @iquito. Is your project open source? Ideally the best way to debug is if I could get a copy to run against but I know that might not be possible.

One idea to try is modifying the `commitsSince` value in the config file. I'm wondering if the number of commits is somehow affecting the performance. If you try a small value like "1 Week Ago" I'm curious to see what happens.

**Comment by iquito** [comment]
Unfortunately it is not open source. I tried a few things now:

- I downgraded to PHP 7.1.11 - still hangs.
- I also chose a directory with only one php file in it - still hangs.
- I created a churn.yml with `commitsSince: One day ago` - still hangs.
- I tried it with two other projects, with completely different git repositories and files (one with 370 commits, one with about 50 commits) - with both projects it hangs, as soon as I select a directory with just one PHP file in it.
- If I select a directory with no PHP files in it, then it finishes (and shows an empty list).

So not sure what this could be. I had it running for 3 hours just before, and it still didn't finish, which would suggest some kind of infinite loop somewhere.

**Comment by bmitch** [comment]
@iquito Are you able to make a small code base that duplicates the issue? I think I'm going to have to have a code base it can be easily duplicated on in order to debug.

**Comment by iquito** [comment]
After setting a timeout for PHP, I noticed that the process runner never ended, churn-php got stuck in places like these:

- vendor/bmitch/churn-php/src/Processes/ChurnProcess.php on line 57
- vendor/bmitch/churn-php/src/Managers/ProcessManager.php on line 72
- vendor/bmitch/churn-php/src/Managers/ProcessManager.php on line 45
- vendor/bmitch/churn-php/src/Managers/ProcessManager.php on line 71

I then checked what commands are run, and there found the problem: My project directories have spaces in them. If you try to run churn-php and there is a space anywhere in the path, then git returns with a fatal error (because it cannot find the directory) and somehow churn-php never notices that and checks on the process forever.

So in `Churn\Factories\ProcessFactory` on line 34 and 35, `getcwd()` and `$file->getFullPath()` need quotes around them. Additionally, there should be a way for churn-php to detect if a process failed - as far as I can see it just checks if it was successful, but never if it failed.

**Comment by bmitch** [comment]
OK great thanks for your detective work @iquito 

Feel free to submit a PR if you have time. Otherwise I will get to it when I have a chance or if someone else wants to step in please be my guest.

**Comment by iquito** [comment]
I created a PR for escaping the arguments - with that it works again as intended. It could still be worth it to rework the whole process handling to detect when a process failed and show an error message to the developer instead of just ending up in a infinite loop.

**Comment by bmitch** [comment]
Thanks @iquito feel free to open another issue for the process handling enhancement you menthioed.

Main issue is fixed by #174
