### ISSUE TITLE
Check for ".git" file before running

### ISSUE THREAD

**Issue by bmitch** [bmitch/churn-php#173]
As reported here:

https://github.com/bmitch/churn-php/pull/127#issuecomment-360773418

If you run churn and there is no .git file present you get an error.

Would be nice to catch this and present a user friendly error message.

**Comment by bearzk** [comment]
let me give this a try :)

**Comment by bmitch** [comment]
It's all yours @bearzk  :)

**Comment by villfa** [comment]
A new configuration `vcs` has been added with #260 (`git` by default).
If the analyzed project is not versioned by a supported VCS the configuration should be set to `none`.
