### ISSUE TITLE
Expected a value greater than 0. Got: 0

### ISSUE THREAD

**Issue by luchianenco** [bmitch/churn-php#179]
Installed the package, my code is in src folder. Executed the command
```
bin/churn run src
```

and got the error

```
Expected a value greater than 0. Got: 0
```

What is wrong?

**Comment by bmitch** [comment]
Hey @luchianenco, is it possible you do not have a `.git` folder in your project? This has come up one time previously and this was the issue. See the comment here: https://github.com/bmitch/churn-php/pull/127#issuecomment-360773418

If you do have a `.git` folder and this is still happening could you please provide more details?

* Is there more to the error message than that such as the offending class and line number?
* Is your package open source? If so, I could clone and attempt to duplicate myself.

Thanks.

**Comment by steache** [comment]
I've encountered the problem too.

The problem for me was, that you have to be in the folder, where your .git folder is.

Given you have source codes in **/home/example/(.git, src)**, you have to be in **/home/example/** in order to run **churn run src** successfully. :)

I hope this helps someone. Nice project btw. :)

**Comment by saikillua98** [comment]
Mine project use svn，so  how should i do make it works ,thanks!!!!!!

**Comment by bmitch** [comment]
Sorry @saikillua98 - SVN is not supported, only git. See https://github.com/bmitch/churn-php#compatibility

**Comment by ilyachase** [comment]
Maybe we can add another optional parameter for path to directory which contain .git?

**Comment by bmitch** [comment]
@ilyachase those sound like good ideas. I'm open to pull requests. Currently I do not have much time to work on it unfortunately.

**Comment by villfa** [comment]
Relate to #173

**Comment by villfa** [comment]
#261 fixes the original problem.

> Given you have source codes in **/home/example/(.git, src)**, you have to be in **/home/example/** in order to run **churn run src** successfully. :)

This problem has been fixed by #257. You can now run Churn from outside your project..
