### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Yaml\Yaml::parse() must be of the type string, boolean given, called in /app/vendor/bmitch/churn-php/src/Commands/ChurnCommand.php

### ISSUE THREAD

**Issue by ricardofiorani** [bmitch/churn-php#183]
PHP version : PHP 7.1.16

When I run `vendor/bin/churn  run src` I get the following error:

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Yaml\Yaml::parse() must be of the type string, boolean given, called in /app/vendor/bmitch/churn-php/src/Commands/ChurnCommand.php on line 81 and defined in /app/vendor/symfony/yaml/Yaml.php:76
Stack trace:
#0 /app/vendor/bmitch/churn-php/src/Commands/ChurnCommand.php(81): Symfony\Component\Yaml\Yaml::parse(false)
#1 /app/vendor/symfony/console/Command/Command.php(251): Churn\Commands\ChurnCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /app/vendor/symfony/console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /app/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Churn\Commands\ChurnCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleO in /app/vendor/symfony/yaml/Yaml.php on line 76

Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Yaml\Yaml::parse() must be of the type string, boolean given, called in /app/vendor/bmitch/churn-php/src/Commands/ChurnCommand.php on line 81 and defined in /app/vendor/symfony/yaml/Yaml.php on line 76

TypeError: Argument 1 passed to Symfony\Component\Yaml\Yaml::parse() must be of the type string, boolean given, called in /app/vendor/bmitch/churn-php/src/Commands/ChurnCommand.php on line 81 in /app/vendor/symfony/yaml/Yaml.php on line 76

Call Stack:
    0.0026     364176   1. {main}() /app/vendor/bmitch/churn-php/bin/churn:0
    0.1916    3149440   2. Symfony\Component\Console\Application->run() /app/vendor/bmitch/churn-php/bin/churn:16
    0.2159    3468728   3. Symfony\Component\Console\Application->doRun() /app/vendor/symfony/console/Application.php:145
    0.2161    3468728   4. Symfony\Component\Console\Application->doRunCommand() /app/vendor/symfony/console/Application.php:262
    0.2161    3468728   5. Churn\Commands\ChurnCommand->run() /app/vendor/symfony/console/Application.php:886
    0.2164    3473944   6. Churn\Commands\ChurnCommand->execute() /app/vendor/symfony/console/Command/Command.php:251
    0.2197    3503536   7. Symfony\Component\Yaml\Yaml::parse() /app/vendor/bmitch/churn-php/src/Commands/ChurnCommand.php:81

**Comment by bmitch** [comment]
Hey @ricardofiorani thanks for the bug report and the pull request.

I am curious if you know why the bug is occurring? Do you have a YAML config file you are using that is causing this? If so can you please provide it?

Or is the issue the absence of a YAML config file? Or possible something else? Thank you.

**Comment by ricardofiorani** [comment]
I think the problem is the lack of YAML file.

As `file_get_contents()` [returns either string or bool](http://php.net/manual/en/function.file-get-contents.php), and `Symfony/Yaml:parse()` [now typehints the input as string](https://github.com/symfony/yaml/blob/master/Yaml.php#L76), we get the mentioned error.
