### ISSUE TITLE
More verbosity

### ISSUE THREAD

**Issue by ilyachase** [bmitch/churn-php#199]
Hi guys, thanks for such interesting tool.

I have a project with about 8 years of history (transferred from SVN to GIT couple years ago), 100+ Mb of code and thousands of files.

Just for fun I tried to use this tool on it, but it hangs for more than 20 mins with 100% of four of my CPU cores loaded. Question is, can we maybe add some verbosity mode with progress status, so people would be able to estimate how long analysis will take?

**Comment by bmitch** [comment]
That is a good idea. Were you thinking of something like a progress bar?

Another note for you is you can restrict the amount of time it will go back in the history which may help speed it up for you. See the `commitsSince` config setting under https://github.com/bmitch/churn-php#how-to-configure

**Comment by ilyachase** [comment]
> Were you thinking of something like a progress bar?

Yea, just some kind of progress bar would be great.

And thanks, I saw `commitsSince` parameter but I wanted to analyze whole story.

Also I can try to make a pull-request if you want.

**Comment by bmitch** [comment]
That would be great @ilyachase I would be open to a pull-request for sure.
