### ISSUE TITLE
[Improvement] Work with GIT submodules

### ISSUE THREAD

**Issue by Yivan** [bmitch/churn-php#214]
Hello,

We have a main project with GIT submodules.

Running `docker run --rm -ti -v $PWD:/app dockerizedphp/churn run /app/src/MySubmodule` report wrong number of commit (it reports the number of commit of the commit in the main repository for the pointer to the submodule, not the commits of submodule itself).

As our CI run only tests from the main project, we cannot use churn for now.

Solution:
In case of submodule it should report the numer of commit of this file inside the submodule.

Thanks!

**Comment by bmitch** [comment]
Thanks for letting me know.

Sorry it does not work for you. At this time I don't have much time to work on churn but if you (or someone else reading this) wants to provide a PR that solves this issue I will review it.

Another possible solution is to run churn on the repository of the submodule in its own CI pipeline. But perhaps that will not work for your situation?

Thanks.

**Comment by Yivan** [comment]
Thanks for your return on this.
Our CI is only run on the main repo with the submodules installed.
For now we cannot use it.

I change the title as improvement, and hoping one day we will be able!
Thanks

**Comment by villfa** [comment]
Fixed by #257

**Comment by Yivan** [comment]
Thanks ! : )
