### ISSUE TITLE
Is there any plan to adapt to the latest version?

### ISSUE THREAD

**Issue by yankewei** [bmitch/churn-php#215]
Symfony related dependencies have been upgraded to 5.0 or higher, is there any plan to adapt to the latest version?

**Comment by bmitch** [comment]
@yankewei thanks for the question. Currently I have no free time to work on this project but if someone feels like they'd like to make a PR I am open to that. Or if anyone else would like to become a repo collaborator I'd also be open to that.

**Comment by villfa** [comment]
I reopen this issue since #217 had to be rollbacked.

**Comment by villfa** [comment]
Fixed by #226
