### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by bmitch** [bmitch/churn-php#222]
I'm looking for someone to take over maintaining this repository.

When I started this repository I had much more free time than I do now. I feel bad that people are actively creating pull requests and I'm not available to really help much.

If you are interested please reply to this issue. I have no idea if I'll get any interest or not. Thanks!

**Comment by villfa** [comment]
Hi @bmitch,
I'd like to offer my help.
I've already participate to this project and will be glad to do more.
Let me know if you need to know more about me.

**Comment by bmitch** [comment]
Thanks @villfa I'll send you an email!
