### ISSUE TITLE
Configure `git` path command

### ISSUE THREAD

**Issue by ckimn** [bmitch/churn-php#348]
Hi,

I want to launch `churn` in my CI but the number of files changes are not detected.

In https://github.com/bmitch/churn-php/blob/master/src/Process/ChangesCount/GitChangesCountProcess.php the git command can't be set.

The path to `git` is ` /usr/bin/git ` in Github Actions for example.

A configuration option for this parameter can be set ? Like `vcs_path` ?

Thank you

**Comment by villfa** [comment]
Hi @ckimn,

It's an interesting suggestion but, given the description of your problem, I'm not sure it's the right solution for you.

How do you configure [`actions/checkout`](https://github.com/actions/checkout)? Do you specify a value for `fetch-depth`? If not, set it to `0` and it should work as expected.

Please tell me if my assumption is wrong.

**Comment by ckimn** [comment]
oh yes indeed `actions/checkout` was misconfigured.

It works as expected, thank you very much!
