### ISSUE TITLE
Only displays 5 files instead of 10

### ISSUE THREAD

**Issue by vincent-debes** [bmitch/churn-php#389]
Hi,

I am testing churn-php, here is my configuration (I kept it simple): 
```
filesToShow: 10
minScoreToShow: 0
cachePath: .churn.cache
directoriesToScan:
 - src
```
The result outputs only 5 files. I know for sure the `filesToShow` value is taken into account since it displays 3 files if I put 3 instead of 10. But nothing above 5, it sticks to 5 files displayed and I cannot figure out what is missing to get 10 (or more) files in the list.

Any help appreciated. Thanks for this great tool by the way!

**Comment by villfa** [comment]
Hello @vincent-debes ,
I think this is related with #366.
Since the score can be negative, by decreasing `minScoreToShow` you should be able to see the other files.

This is not an intuitive behaviour and it will most probably change in the next major version.

**Comment by vincent-debes** [comment]
That was the problem! Thanks for your help.
