### ISSUE TITLE
[Config] Paths of files

### ISSUE THREAD

**Issue by bmitch** [bmitch/churn-php#57]
Stems from #40

**Comment by bmitch** [comment]
Allow user to configure that path (or paths) of the source files it should process.

**Comment by josephzidell** [comment]
@bmitch Would you like me to attempt a PR?

**Comment by bmitch** [comment]
@josephzidell You bet! That would be great, thanks.

**Comment by josephzidell** [comment]
@bmitch Running on a folder with 1 file, 8 LOC. My CPU is up to 30% and it's been running for over 3 mins, still no results. Windows 10, PHP 7.1.0

**Comment by josephzidell** [comment]
Figured it out. `ProcessFactory.php` uses `uniq` which isn't available on Windows systems. This should be documented in the readme.

**Comment by josephzidell** [comment]
Seems like this was fixed 2 days ago in commit `181c574415fedc057701d1db9d7fae487fabc5b2`?

**Comment by bmitch** [comment]
@josephzidell That's true, `ProcessFactory.php` does use `uniq`. I've added #70 to make a note of that in the readme. I'll also see if there's a command I could use that would work for both platforms. Thanks for catching that.

As for 181c574415fedc057701d1db9d7fae487fabc5b2, that commit is for ignoring files.

So if you ran the command like `vendor/bin/churn run src` and had this in your churn.yml file:

```yml
filesToIgnore:
 - src/Commands/ChurnCommand.php
```

Then that file would be ignored in the processing.

This issue is to allow one (or perhaps many) paths to be configured in the churn.yml file. So for example, say you wanted it to process the files found within your `src` and `tests` folders. Currently, the only way to do this would be to run the command twice, each time on each folder:

`vendor/bin/churn run src`
`vendor/bin/churn run tests`

So I thought it would be nice in the churn.yml file you could configure this like:

```yml
folders:
 - src
 - tests
```
Then the user would just have to run

`vendor/bin/churn run`

Which would then process the files in those folders.

**Comment by josephzidell** [comment]
I thought we wanted to exclude directories, which currently **is** possible. Will do a PR for multiple dirs in the command.

**Comment by bmitch** [comment]
Sorry, I should have been more clear initially in the issue :sweat_smile: Thanks!

**Comment by josephzidell** [comment]
Unable to run the tests due to my Windows system.
