### ISSUE TITLE
Add sniff to check for use of: instanceof

### ISSUE THREAD

**Issue by Exadra37** [bmitch/churn-php#61]
A sniff to disallow the use of [instanceof](http://php.net/manual/en/internals2.opcodes.instanceof.php) function would be good to have.

The use of it is a code smell and represents a flaw in the project Software Architecture.

I love this package that helps us to write more SOLID and Clean Code.

**Comment by bmitch** [comment]
@Exadra37 I believe you have mistakenly added an issue in this project which was meant for https://github.com/bmitch/Codor/

I will close this, please feel free to add an issue to the project above.
