### ISSUE TITLE
Doesn't work in windows.

### ISSUE THREAD

**Issue by bmitch** [bmitch/churn-php#71]
Because of this line:

https://github.com/bmitch/churn-php/blob/master/src/Factories/ProcessFactory.php#L35

Is there another command that will do the same thing that works in Windows and Unix?

**Comment by josephzidell** [comment]
Can you perform those operations in PHP?

**Comment by bmitch** [comment]
Quite possibly. Is definitely worth looking into. I'll probably have some time in the coming week to look. But if you are feeling up for it please feel free.

**Comment by MZAWeb** [comment]
Works fine on Bash for Windows 10

**Comment by bmitch** [comment]
I haven't had time to check into this. If anyone else feels like taking a stab at this please feel free.

**Comment by villfa** [comment]
It's worth mentioning that the problem in the line comes from the command `uniq` which doesn't exists in Windows.

But there is another problem which is not related to Windows:
https://github.com/bmitch/churn-php/blob/60b09ede5185f04d2e5b85866505ebafd1ad4289/src/Commands/ChurnCommand.php#L142-L143

The script runs forever if a process is terminated but not successful.

**Comment by bmitch** [comment]
Thanks @villfa , are you able to provide an example that makes the script run forever?

**Comment by villfa** [comment]
You can enter an infinite loop by running *churn* on a folder containing a space character.
```
./vendor/bin/churn run my\ project
```

The command line returns an error because it is built without using [escapeshellarg](http://php.net/manual/fr/function.escapeshellarg.php).

**Comment by josephzidell** [comment]
To brush the dust off of this and provide value for Windows users, would you be willing to accept a PR that refactors https://github.com/bmitch/churn-php/blob/master/src/Factories/ProcessFactory.php#L34-L36 to a pure PHP implementation?

**Comment by bmitch** [comment]
@josephzidell yes that would be great!

**Comment by tomasfejfar** [comment]
Regarding the escapeshellarg - you can [supply parameters one-by-one as array](https://symfony.com/doc/current/components/process.html#using-features-from-the-os-shell) with Symfony process.
