### ISSUE TITLE
Make multiple paths (#72) something that be configured in churn.yml

### ISSUE THREAD

**Issue by bmitch** [bmitch/churn-php#76]
For that for this feature I'd also want the user to be able to provide the paths via the churn.yml file if they like.

Possibly like:

```yml
folders:
 - src
 - tests
```

**Comment by matthiasnoback** [comment]
It doesn't seem like anyone is working on this, so I'd like to pick this up.

**Comment by bmitch** [comment]
Thanks @matthiasnoback it is all yours :)

**Comment by bmitch** [comment]
Resolved by #125
