### ISSUE TITLE
Sniff to disallow set methods.

### ISSUE THREAD

**Issue by Exadra37** [bmitch/churn-php#93]
Using set methods in a class is not advised, because:
* if the class is instantiated and we forget to call the set methods it may work or not and cause side effects. Plus we may need to call them in the correct order. 
* if you need to inject Collaborators they must be strictly injected via constructor and any other values needed by the class should be passed as arguments to the method being called, preferable using Immutable Value Objects(the only exception to not inject an object via constructor).
* objects are passed by reference in Php, therefore when the object is passed around any call to the set method will affect all places where the object is being used. This can cause undesired bugs, that sometimes are hard to track.

I can continue with more cases why we should not use set methods, but I think the above 3 ones are strong enough to justify the sniff.

Thanks for your excellent work.

**Comment by bmitch** [comment]
Sorry @Exadra37 I think you have the wrong project. Were you thinking of https://github.com/bmitch/Codor ?

**Comment by bmitch** [comment]
See https://github.com/bmitch/churn-php/issues/93

**Comment by Exadra37** [comment]
@bmitch this is not Gitlab where we can cross reference issues between repos... your last comment points to itself ;)

Sorry to open the issue in the wrong repo :(

**Comment by bmitch** [comment]
Thanks @Exadra37 I updated it :smiley:
