### ISSUE TITLE
Support mercurial/svn/etc.

### ISSUE THREAD

**Issue by rvanvelzen** [bmitch/churn-php#95]
Though git is the most popular, mercurial is heavily used as well and it would be interesting to put this to use.

**Comment by bmitch** [comment]
Thanks for the suggestion @rvanvelzen.

I don't have access to mecurial or svn so wouldn't be able to work on this. But if someone out there wants to provide a pull request I'd be open the possiblity.

**Comment by villfa** [comment]
I close this issue since it is too broad. See #274 and #275 instead.

**Comment by villfa** [comment]
FYI [Churn 1.4.0](https://github.com/bmitch/churn-php/releases/tag/1.4.0) supports Mercurial, Subversion and also Fossil.
